export const data = {
  '-99': 'Network disconnected, please check the network',
  '-1': 'Network anomaly',
  408: 'Request timeout, please try again later',
  500: 'Server exception, please try again later',
  9999: 'Network anomaly',
  10000: 'No access rights',
  10001: 'No permission to perform this operation',
  10002: 'Invalid parameters',
  10003: 'The remote procedure call failed',
  10004: 'No access, exit after 5s',
  10006: 'This request canceled',
  10007: 'Status revoked',
  10101: 'Record does not exist',
  10102: 'Record expired',
  10103: 'Invalid token',
  10104: 'Invalid verification code',
  10105: 'The application has been submited by other，please wait',
  20101: 'Incorrect username or password',
  20102: 'User exists',
  20103: 'Invalid signature',
  20104: 'Wrong password',
  20105: 'Wrong password',
  20106: 'Link expired',
  20107: 'User not registerd',
  20108: 'You cannot delete yourself',
  20109: 'This device has been linked to the user',
  20110: 'Name of the member  exist',
  20111: 'The member exist',
  20112: 'This member is in other workspace',
  20113: 'This member has been deleted',
  20114: 'The creator of the workspace cannot be deleted',
  20115: 'Please reset your keyauth APP',
  20116: 'Please prompt the added person to reset APP，after that he can be added again',
  21100: 'The KeyAuth public key has been used. Please reset KeyAuth',
  30101: 'Corporte  exists',
  30102: 'Corporate initialised',
  30103: 'Invitation record does\'t exist',
  30104: 'The email has been used',
  30105: 'The email has been used',
  30106: 'The workspace has not been initialized yet, please wait',
  30107: 'The company account has been closed, exit after 5s',
  30108: 'Date occurs before the starting date, please contact keystore staff',
  30109: 'The company account is frozen, exit after 5s',
  30110: 'Account expired, exit after 5s',
  40101: 'Insufficient token',
  40102: 'The asset has been added!',
  40103: 'Transaction on process, please wait',
  40104: 'Unsupported token',
  40105: 'Wrong recipient\'s address',
  40106: 'Exceeds quota per day',
  40107: 'Exceeds quota per transaction',
  40108: 'Insufficient gas',
  40109: 'Payment address and recipient\'s address can\'t be the same',
  40110: 'The user access cannot be set as \'viewers only',
  40111: 'USDT transfer failed',
  40112: 'USDT transfer has\'t completed',
  40113: 'Insufficient BTC for transaction fee and the addtional amount',
  40114: 'Cannot make transfers between different Tether protocals',
  40115: 'Account exists',
  40116: 'ETH transfer is too fast',
  40117: 'Insufficient balance of USDT',
  40118: 'Duplicate wallet name',
  40119: 'The recipient does not exist',
  40120: 'The address does not exist',
  40121: 'This recipient information is in change，please wait',
  40122: 'The recipient does not exist，this request canceled',
  40123: 'The address does not exist，this request canceled',
  40124: 'This recipient has been deleted',
  40125: 'The recipient has been deleted，the request canceled',
  40126: 'Insufficient ETH token ',
  40127: 'This account is frozen',
  40128: 'Transfer out or change amount is too small, please re-enter',
  40129: 'Node response transaction timeout, please refer to the data on the chain to avoid duplicate transfer',
  40130: 'There is a wrong private key fragment in the transfer auditor, please contact the account administrator to reset',
  40131: 'The balance of archived account cannot exceed 10usdt, please transfer out and try to archive again',
  50101: 'User authorised',
  50102: 'Approved',
  50103: 'Declined',
  50104: 'Please set up Workspace admin',
  50105: 'No pending approvals',
  50106: 'Expired',
  50107: 'The authorization canceled',
  50108: 'Duplicate payee address',
  50109: 'Duplicate payee name',
  60101: 'The whitelist admin has been deleted, please reset',
  60102: 'The user has  pending approvals',
  60103: 'There have been changes made to the Corporate private key holders, the approval is canceled',
  60104: 'There have been changes made to the payment authorisers, the payment is now invalid',
  60105: 'There have been changes made to the Workspace admin, the approval is canceled',
  60106: 'There have been changes made to the Workspace admin, the approval is canceled',
  60107: 'Authorisation rules invalid,please reset',
  60108: 'Authorisation rules invalid,please reset',
  60109: 'The rule of create wallet revoked，please restore the private key by the backup',
  60110: 'The rule of change private key holder revoked，please restore the private key by the backup',
  60111: 'The rule of reset transfer authoriser revoked，please restore the private key by the backup',
  60112: 'The rule of transfer authorisation revoked，please reset the transfer authoriser',
  60113: 'The rule of authorisation revoked ，the request canceled',
  60114: '${personName} has been deleted',
  60115: '${personName} has been given other acces',
  60116: '${personName} has been given other acces',
  70101: 'Start Date cannot be greater than End Date',
  70102: 'Only from the most recent three years with less than one year\'s length can be generated',
  70103: 'Start Date and End Date must be before the present day and cannot be the present day',
  70104: '${address} is a address in ${walletName}',
  70105: '${address} has been added to ${contactName}',
  70106: 'The name of recipient cannot be the same with wallet',
  70107: 'Recipient exit',
  70108: 'The rule of recipient authorisation revoked，please reset the workspace admin',
  70109: 'The rule of recipient authorisation revoked ，please reset',
  70110: 'The rule of recipient authorisation revoked ，the request canceled',
  70111: 'The recipient has been added，the request canceled',
  70112: '${address}is internal ${walletName} address ，the request canceled',
  70113: '${address} has been added，the request canceled',
  80001: 'No transaction was conducted',
  80002: 'The report has been deleted',
  50000002: 'Invitation code does not exist',
  50000003: 'Invitation code is used',
  50000004: 'Account expired, please contact keystore staff',
  50000005: 'Invitation code failed to be sent',
  50000006: 'Indicates that the invitation code was generated but not sent',
  50000008: 'Date occurs before the starting date, please contact keystore staff',
};