export const type = {
  EXTRACT_AUTHORITY_WALLET: 'EXTRACT_AUTHORITY_WALLET',
  EXTRACT_AUTHORITY_ORGANIZATION: 'EXTRACT_AUTHORITY_ORGANIZATION',
  TO_AUDITING_SEND_TOKEN: 'TO_AUDITING_SEND_TOKEN',
  TO_AUDITING_CHANGE_WALLET_KEY_HOLDER: 'TO_AUDITING_CHANGE_WALLET_KEY_HOLDER',
  TO_AUDITING_RESET_WALLET_KEY_HOLDER: 'TO_AUDITING_RESET_WALLET_KEY_HOLDER',
  TO_AUDITING_BACKUPS_ORGANIZATION_KEY_APPLY: 'TO_AUDITING_BACKUPS_ORGANIZATION_KEY_APPLY',
  TO_AUDITING_CREATE_WALLET: 'TO_AUDITING_CREATE_WALLET',
  TO_AUDITING_ADD_OUTER_CONTACT: 'TO_AUDITING_ADD_OUTER_CONTACT',
  TO_AUDITING_CHANGE_ORG_KEY_HOLDER: 'TO_AUDITING_CHANGE_ORG_KEY_HOLDER',
  TO_AUDITING_EDIT_OUTER_CONTACT: 'TO_AUDITING_EDIT_OUTER_CONTACT'
};